// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static UILHost.Web.Controllers.AccountController Account = new UILHost.Web.Controllers.T4MVC_AccountController();
    public static UILHost.Web.Controllers.ErrorController Error = new UILHost.Web.Controllers.T4MVC_ErrorController();
    public static UILHost.Web.Controllers.HomeController Home = new UILHost.Web.Controllers.T4MVC_HomeController();
    public static UILHost.Web.Controllers.MeetController Meet = new UILHost.Web.Controllers.T4MVC_MeetController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        public static readonly string benefitmall_pavlos_grid_plugin_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/benefitmall.pavlos.grid.plugin.min.js") ? Url("benefitmall.pavlos.grid.plugin.min.js") : Url("benefitmall.pavlos.grid.plugin.js");
        public static readonly string bootbox_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootbox.min.js") ? Url("bootbox.min.js") : Url("bootbox.js");
        public static readonly string bootbox_min_js = Url("bootbox.min.js");
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        public static readonly string jquery_1_10_2_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.10.2.intellisense.min.js") ? Url("jquery-1.10.2.intellisense.min.js") : Url("jquery-1.10.2.intellisense.js");
        public static readonly string jquery_1_10_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.10.2.min.js") ? Url("jquery-1.10.2.min.js") : Url("jquery-1.10.2.js");
        public static readonly string jquery_1_10_2_min_js = Url("jquery-1.10.2.min.js");
        public static readonly string jquery_1_10_2_min_map = Url("jquery-1.10.2.min.map");
        public static readonly string jquery_migrate_1_2_1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-migrate-1.2.1.min.js") ? Url("jquery-migrate-1.2.1.min.js") : Url("jquery-migrate-1.2.1.js");
        public static readonly string jquery_migrate_1_2_1_min_js = Url("jquery-migrate-1.2.1.min.js");
        public static readonly string jquery_mask_min_js = Url("jquery.mask.min.js");
        public static readonly string jquery_unobtrusive_ajax_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.unobtrusive-ajax.min.js") ? Url("jquery.unobtrusive-ajax.min.js") : Url("jquery.unobtrusive-ajax.js");
        public static readonly string jquery_unobtrusive_ajax_min_js = Url("jquery.unobtrusive-ajax.min.js");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Kendo {
            private const string URLPATH = "~/Scripts/Kendo";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string jquery_min_js = Url("jquery.min.js");
            public static readonly string jquery_min_map = Url("jquery.min.map");
            public static readonly string kendo_autocomplete_min_js = Url("kendo.autocomplete.min.js");
            public static readonly string kendo_autocomplete_min_js_map = Url("kendo.autocomplete.min.js.map");
            public static readonly string kendo_binder_min_js = Url("kendo.binder.min.js");
            public static readonly string kendo_binder_min_js_map = Url("kendo.binder.min.js.map");
            public static readonly string kendo_button_min_js = Url("kendo.button.min.js");
            public static readonly string kendo_button_min_js_map = Url("kendo.button.min.js.map");
            public static readonly string kendo_calendar_min_js = Url("kendo.calendar.min.js");
            public static readonly string kendo_calendar_min_js_map = Url("kendo.calendar.min.js.map");
            public static readonly string kendo_colorpicker_min_js = Url("kendo.colorpicker.min.js");
            public static readonly string kendo_colorpicker_min_js_map = Url("kendo.colorpicker.min.js.map");
            public static readonly string kendo_columnmenu_min_js = Url("kendo.columnmenu.min.js");
            public static readonly string kendo_columnmenu_min_js_map = Url("kendo.columnmenu.min.js.map");
            public static readonly string kendo_combobox_min_js = Url("kendo.combobox.min.js");
            public static readonly string kendo_combobox_min_js_map = Url("kendo.combobox.min.js.map");
            public static readonly string kendo_core_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/kendo.core.min.js") ? Url("kendo.core.min.js") : Url("kendo.core.js");
            public static readonly string kendo_core_min_js_map = Url("kendo.core.min.js.map");
            public static readonly string kendo_data_min_js = Url("kendo.data.min.js");
            public static readonly string kendo_data_min_js_map = Url("kendo.data.min.js.map");
            public static readonly string kendo_data_odata_min_js = Url("kendo.data.odata.min.js");
            public static readonly string kendo_data_odata_min_js_map = Url("kendo.data.odata.min.js.map");
            public static readonly string kendo_data_signalr_min_js = Url("kendo.data.signalr.min.js");
            public static readonly string kendo_data_signalr_min_js_map = Url("kendo.data.signalr.min.js.map");
            public static readonly string kendo_data_xml_min_js = Url("kendo.data.xml.min.js");
            public static readonly string kendo_data_xml_min_js_map = Url("kendo.data.xml.min.js.map");
            public static readonly string kendo_datepicker_min_js = Url("kendo.datepicker.min.js");
            public static readonly string kendo_datepicker_min_js_map = Url("kendo.datepicker.min.js.map");
            public static readonly string kendo_datetimepicker_min_js = Url("kendo.datetimepicker.min.js");
            public static readonly string kendo_datetimepicker_min_js_map = Url("kendo.datetimepicker.min.js.map");
            public static readonly string kendo_draganddrop_min_js = Url("kendo.draganddrop.min.js");
            public static readonly string kendo_draganddrop_min_js_map = Url("kendo.draganddrop.min.js.map");
            public static readonly string kendo_dropdownlist_min_js = Url("kendo.dropdownlist.min.js");
            public static readonly string kendo_dropdownlist_min_js_map = Url("kendo.dropdownlist.min.js.map");
            public static readonly string kendo_editable_min_js = Url("kendo.editable.min.js");
            public static readonly string kendo_editable_min_js_map = Url("kendo.editable.min.js.map");
            public static readonly string kendo_editor_min_js = Url("kendo.editor.min.js");
            public static readonly string kendo_editor_min_js_map = Url("kendo.editor.min.js.map");
            public static readonly string kendo_filtermenu_min_js = Url("kendo.filtermenu.min.js");
            public static readonly string kendo_filtermenu_min_js_map = Url("kendo.filtermenu.min.js.map");
            public static readonly string kendo_fx_min_js = Url("kendo.fx.min.js");
            public static readonly string kendo_fx_min_js_map = Url("kendo.fx.min.js.map");
            public static readonly string kendo_grid_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/kendo.grid.min.js") ? Url("kendo.grid.min.js") : Url("kendo.grid.js");
            public static readonly string kendo_grid_min_js_map = Url("kendo.grid.min.js.map");
            public static readonly string kendo_groupable_min_js = Url("kendo.groupable.min.js");
            public static readonly string kendo_groupable_min_js_map = Url("kendo.groupable.min.js.map");
            public static readonly string kendo_imagebrowser_min_js = Url("kendo.imagebrowser.min.js");
            public static readonly string kendo_imagebrowser_min_js_map = Url("kendo.imagebrowser.min.js.map");
            public static readonly string kendo_list_min_js = Url("kendo.list.min.js");
            public static readonly string kendo_list_min_js_map = Url("kendo.list.min.js.map");
            public static readonly string kendo_listview_min_js = Url("kendo.listview.min.js");
            public static readonly string kendo_listview_min_js_map = Url("kendo.listview.min.js.map");
            public static readonly string kendo_maskedtextbox_min_js = Url("kendo.maskedtextbox.min.js");
            public static readonly string kendo_maskedtextbox_min_js_map = Url("kendo.maskedtextbox.min.js.map");
            public static readonly string kendo_menu_min_js = Url("kendo.menu.min.js");
            public static readonly string kendo_menu_min_js_map = Url("kendo.menu.min.js.map");
            public static readonly string kendo_mobile_actionsheet_min_js = Url("kendo.mobile.actionsheet.min.js");
            public static readonly string kendo_mobile_actionsheet_min_js_map = Url("kendo.mobile.actionsheet.min.js.map");
            public static readonly string kendo_mobile_application_min_js = Url("kendo.mobile.application.min.js");
            public static readonly string kendo_mobile_application_min_js_map = Url("kendo.mobile.application.min.js.map");
            public static readonly string kendo_mobile_loader_min_js = Url("kendo.mobile.loader.min.js");
            public static readonly string kendo_mobile_loader_min_js_map = Url("kendo.mobile.loader.min.js.map");
            public static readonly string kendo_mobile_pane_min_js = Url("kendo.mobile.pane.min.js");
            public static readonly string kendo_mobile_pane_min_js_map = Url("kendo.mobile.pane.min.js.map");
            public static readonly string kendo_mobile_popover_min_js = Url("kendo.mobile.popover.min.js");
            public static readonly string kendo_mobile_popover_min_js_map = Url("kendo.mobile.popover.min.js.map");
            public static readonly string kendo_mobile_scroller_min_js = Url("kendo.mobile.scroller.min.js");
            public static readonly string kendo_mobile_scroller_min_js_map = Url("kendo.mobile.scroller.min.js.map");
            public static readonly string kendo_mobile_shim_min_js = Url("kendo.mobile.shim.min.js");
            public static readonly string kendo_mobile_shim_min_js_map = Url("kendo.mobile.shim.min.js.map");
            public static readonly string kendo_mobile_view_min_js = Url("kendo.mobile.view.min.js");
            public static readonly string kendo_mobile_view_min_js_map = Url("kendo.mobile.view.min.js.map");
            public static readonly string kendo_multiselect_min_js = Url("kendo.multiselect.min.js");
            public static readonly string kendo_multiselect_min_js_map = Url("kendo.multiselect.min.js.map");
            public static readonly string kendo_notification_min_js = Url("kendo.notification.min.js");
            public static readonly string kendo_notification_min_js_map = Url("kendo.notification.min.js.map");
            public static readonly string kendo_numerictextbox_min_js = Url("kendo.numerictextbox.min.js");
            public static readonly string kendo_numerictextbox_min_js_map = Url("kendo.numerictextbox.min.js.map");
            public static readonly string kendo_pager_min_js = Url("kendo.pager.min.js");
            public static readonly string kendo_pager_min_js_map = Url("kendo.pager.min.js.map");
            public static readonly string kendo_panelbar_min_js = Url("kendo.panelbar.min.js");
            public static readonly string kendo_panelbar_min_js_map = Url("kendo.panelbar.min.js.map");
            public static readonly string kendo_popup_min_js = Url("kendo.popup.min.js");
            public static readonly string kendo_popup_min_js_map = Url("kendo.popup.min.js.map");
            public static readonly string kendo_progressbar_min_js = Url("kendo.progressbar.min.js");
            public static readonly string kendo_progressbar_min_js_map = Url("kendo.progressbar.min.js.map");
            public static readonly string kendo_reorderable_min_js = Url("kendo.reorderable.min.js");
            public static readonly string kendo_reorderable_min_js_map = Url("kendo.reorderable.min.js.map");
            public static readonly string kendo_resizable_min_js = Url("kendo.resizable.min.js");
            public static readonly string kendo_resizable_min_js_map = Url("kendo.resizable.min.js.map");
            public static readonly string kendo_router_min_js = Url("kendo.router.min.js");
            public static readonly string kendo_router_min_js_map = Url("kendo.router.min.js.map");
            public static readonly string kendo_scheduler_agendaview_min_js = Url("kendo.scheduler.agendaview.min.js");
            public static readonly string kendo_scheduler_agendaview_min_js_map = Url("kendo.scheduler.agendaview.min.js.map");
            public static readonly string kendo_scheduler_dayview_min_js = Url("kendo.scheduler.dayview.min.js");
            public static readonly string kendo_scheduler_dayview_min_js_map = Url("kendo.scheduler.dayview.min.js.map");
            public static readonly string kendo_scheduler_min_js = Url("kendo.scheduler.min.js");
            public static readonly string kendo_scheduler_min_js_map = Url("kendo.scheduler.min.js.map");
            public static readonly string kendo_scheduler_monthview_min_js = Url("kendo.scheduler.monthview.min.js");
            public static readonly string kendo_scheduler_monthview_min_js_map = Url("kendo.scheduler.monthview.min.js.map");
            public static readonly string kendo_scheduler_recurrence_min_js = Url("kendo.scheduler.recurrence.min.js");
            public static readonly string kendo_scheduler_recurrence_min_js_map = Url("kendo.scheduler.recurrence.min.js.map");
            public static readonly string kendo_scheduler_view_min_js = Url("kendo.scheduler.view.min.js");
            public static readonly string kendo_scheduler_view_min_js_map = Url("kendo.scheduler.view.min.js.map");
            public static readonly string kendo_selectable_min_js = Url("kendo.selectable.min.js");
            public static readonly string kendo_selectable_min_js_map = Url("kendo.selectable.min.js.map");
            public static readonly string kendo_slider_min_js = Url("kendo.slider.min.js");
            public static readonly string kendo_slider_min_js_map = Url("kendo.slider.min.js.map");
            public static readonly string kendo_sortable_min_js = Url("kendo.sortable.min.js");
            public static readonly string kendo_sortable_min_js_map = Url("kendo.sortable.min.js.map");
            public static readonly string kendo_splitter_min_js = Url("kendo.splitter.min.js");
            public static readonly string kendo_splitter_min_js_map = Url("kendo.splitter.min.js.map");
            public static readonly string kendo_tabstrip_min_js = Url("kendo.tabstrip.min.js");
            public static readonly string kendo_tabstrip_min_js_map = Url("kendo.tabstrip.min.js.map");
            public static readonly string kendo_timepicker_min_js = Url("kendo.timepicker.min.js");
            public static readonly string kendo_timepicker_min_js_map = Url("kendo.timepicker.min.js.map");
            public static readonly string kendo_timezones_min_js = Url("kendo.timezones.min.js");
            public static readonly string kendo_tooltip_min_js = Url("kendo.tooltip.min.js");
            public static readonly string kendo_tooltip_min_js_map = Url("kendo.tooltip.min.js.map");
            public static readonly string kendo_treeview_min_js = Url("kendo.treeview.min.js");
            public static readonly string kendo_treeview_min_js_map = Url("kendo.treeview.min.js.map");
            public static readonly string kendo_upload_min_js = Url("kendo.upload.min.js");
            public static readonly string kendo_upload_min_js_map = Url("kendo.upload.min.js.map");
            public static readonly string kendo_userevents_min_js = Url("kendo.userevents.min.js");
            public static readonly string kendo_userevents_min_js_map = Url("kendo.userevents.min.js.map");
            public static readonly string kendo_validator_min_js = Url("kendo.validator.min.js");
            public static readonly string kendo_validator_min_js_map = Url("kendo.validator.min.js.map");
            public static readonly string kendo_view_min_js = Url("kendo.view.min.js");
            public static readonly string kendo_view_min_js_map = Url("kendo.view.min.js.map");
            public static readonly string kendo_web_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/kendo.web.min.js") ? Url("kendo.web.min.js") : Url("kendo.web.js");
            public static readonly string kendo_web_min_js_map = Url("kendo.web.min.js.map");
            public static readonly string kendo_window_min_js = Url("kendo.window.min.js");
            public static readonly string kendo_window_min_js_map = Url("kendo.window.min.js.map");
        }
    
        public static readonly string knockout_kendo_min_js = Url("knockout-kendo.min.js");
        public static readonly string modernizr_2_6_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.6.2.min.js") ? Url("modernizr-2.6.2.min.js") : Url("modernizr-2.6.2.js");
        public static readonly string mvcfoolproof_unobtrusive_min_js = Url("mvcfoolproof.unobtrusive.min.js");
        public static readonly string MvcFoolproofJQueryValidation_min_js = Url("MvcFoolproofJQueryValidation.min.js");
        public static readonly string MvcFoolproofValidation_min_js = Url("MvcFoolproofValidation.min.js");
        public static readonly string respond_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/respond.min.js") ? Url("respond.min.js") : Url("respond.js");
        public static readonly string respond_min_js = Url("respond.min.js");
        public static readonly string validation_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/validation.min.js") ? Url("validation.min.js") : Url("validation.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string bootstrap_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap-theme.min.css") ? Url("bootstrap-theme.min.css") : Url("bootstrap-theme.css");
             
        public static readonly string bootstrap_theme_css_map = Url("bootstrap-theme.css.map");
        public static readonly string bootstrap_theme_min_css = Url("bootstrap-theme.min.css");
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
             
        public static readonly string bootstrap_css_map = Url("bootstrap.css.map");
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        public static readonly string custom_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/custom.min.css") ? Url("custom.min.css") : Url("custom.css");
             
        public static readonly string font_awesome_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/font-awesome.min.css") ? Url("font-awesome.min.css") : Url("font-awesome.css");
             
        public static readonly string font_awesome_min_css = Url("font-awesome.min.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class kendo {
            private const string URLPATH = "~/Content/kendo";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class _2014_1_318 {
                private const string URLPATH = "~/Content/kendo/2014.1.318";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Black {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Black";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class BlueOpal {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/BlueOpal";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Bootstrap {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Bootstrap";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Default {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Default";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Flat {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Flat";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class HighContrast {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/HighContrast";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string kendoui_ttf = Url("kendoui.ttf");
                    public static readonly string kendoui_woff = Url("kendoui.woff");
                }
            
                public static readonly string kendo_benefitmallgrid_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/kendo.benefitmallgrid.min.css") ? Url("kendo.benefitmallgrid.min.css") : Url("kendo.benefitmallgrid.css");
                     
                public static readonly string kendo_black_min_css = Url("kendo.black.min.css");
                public static readonly string kendo_black_mobile_min_css = Url("kendo.black.mobile.min.css");
                public static readonly string kendo_blueopal_min_css = Url("kendo.blueopal.min.css");
                public static readonly string kendo_blueopal_mobile_min_css = Url("kendo.blueopal.mobile.min.css");
                public static readonly string kendo_bootstrap_min_css = Url("kendo.bootstrap.min.css");
                public static readonly string kendo_bootstrap_mobile_min_css = Url("kendo.bootstrap.mobile.min.css");
                public static readonly string kendo_common_bootstrap_core_min_css = Url("kendo.common-bootstrap.core.min.css");
                public static readonly string kendo_common_bootstrap_min_css = Url("kendo.common-bootstrap.min.css");
                public static readonly string kendo_common_core_min_css = Url("kendo.common.core.min.css");
                public static readonly string kendo_common_min_css = Url("kendo.common.min.css");
                public static readonly string kendo_default_min_css = Url("kendo.default.min.css");
                public static readonly string kendo_default_mobile_min_css = Url("kendo.default.mobile.min.css");
                public static readonly string kendo_flat_min_css = Url("kendo.flat.min.css");
                public static readonly string kendo_flat_mobile_min_css = Url("kendo.flat.mobile.min.css");
                public static readonly string kendo_highcontrast_min_css = Url("kendo.highcontrast.min.css");
                public static readonly string kendo_highcontrast_mobile_min_css = Url("kendo.highcontrast.mobile.min.css");
                public static readonly string kendo_metro_min_css = Url("kendo.metro.min.css");
                public static readonly string kendo_metro_mobile_min_css = Url("kendo.metro.mobile.min.css");
                public static readonly string kendo_metroblack_min_css = Url("kendo.metroblack.min.css");
                public static readonly string kendo_metroblack_mobile_min_css = Url("kendo.metroblack.mobile.min.css");
                public static readonly string kendo_moonlight_min_css = Url("kendo.moonlight.min.css");
                public static readonly string kendo_moonlight_mobile_min_css = Url("kendo.moonlight.mobile.min.css");
                public static readonly string kendo_rtl_min_css = Url("kendo.rtl.min.css");
                public static readonly string kendo_silver_min_css = Url("kendo.silver.min.css");
                public static readonly string kendo_silver_mobile_min_css = Url("kendo.silver.mobile.min.css");
                public static readonly string kendo_uniform_min_css = Url("kendo.uniform.min.css");
                public static readonly string kendo_uniform_mobile_min_css = Url("kendo.uniform.mobile.min.css");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Metro {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Metro";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class MetroBlack {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/MetroBlack";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Moonlight {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Moonlight";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Silver {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Silver";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class textures {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/textures";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string brushed_metal_png = Url("brushed-metal.png");
                    public static readonly string dots1_png = Url("dots1.png");
                    public static readonly string dots10_png = Url("dots10.png");
                    public static readonly string dots11_png = Url("dots11.png");
                    public static readonly string dots12_png = Url("dots12.png");
                    public static readonly string dots13_png = Url("dots13.png");
                    public static readonly string dots2_png = Url("dots2.png");
                    public static readonly string dots3_png = Url("dots3.png");
                    public static readonly string dots4_png = Url("dots4.png");
                    public static readonly string dots5_png = Url("dots5.png");
                    public static readonly string dots6_png = Url("dots6.png");
                    public static readonly string dots7_png = Url("dots7.png");
                    public static readonly string dots8_png = Url("dots8.png");
                    public static readonly string dots9_png = Url("dots9.png");
                    public static readonly string glass_lighter_png = Url("glass-lighter.png");
                    public static readonly string glass_png = Url("glass.png");
                    public static readonly string highlight_png = Url("highlight.png");
                    public static readonly string hsv_gradient_png = Url("hsv-gradient.png");
                    public static readonly string hue_png = Url("hue.png");
                    public static readonly string leather1_png = Url("leather1.png");
                    public static readonly string leather2_png = Url("leather2.png");
                    public static readonly string noise_png = Url("noise.png");
                    public static readonly string stripe1_png = Url("stripe1.png");
                    public static readonly string stripe2_png = Url("stripe2.png");
                    public static readonly string stripe3_png = Url("stripe3.png");
                    public static readonly string stripe4_png = Url("stripe4.png");
                    public static readonly string stripe5_png = Url("stripe5.png");
                    public static readonly string stripe6_png = Url("stripe6.png");
                    public static readonly string transparency_png = Url("transparency.png");
                    public static readonly string transtexture_png = Url("transtexture.png");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Uniform {
                    private const string URLPATH = "~/Content/kendo/2014.1.318/Uniform";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string editor_png = Url("editor.png");
                    public static readonly string imagebrowser_png = Url("imagebrowser.png");
                    public static readonly string indeterminate_gif = Url("indeterminate.gif");
                    public static readonly string loading_image_gif = Url("loading-image.gif");
                    public static readonly string loading_gif = Url("loading.gif");
                    public static readonly string loading_2x_gif = Url("loading_2x.gif");
                    public static readonly string slider_h_gif = Url("slider-h.gif");
                    public static readonly string slider_v_gif = Url("slider-v.gif");
                    public static readonly string sprite_png = Url("sprite.png");
                    public static readonly string sprite_2x_png = Url("sprite_2x.png");
                }
            
            }
        
        }
    
        public static readonly string reset_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/reset.min.css") ? Url("reset.min.css") : Url("reset.css");
             
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
             
        public static readonly string style_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/style.min.css") ? Url("style.min.css") : Url("style.css");
             
        public static readonly string velcro_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/velcro.min.css") ? Url("velcro.min.css") : Url("velcro.css");
             
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Scripts {}
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Styles {}
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009


